### ISSUE TITLE
Road Map

### ISSUE THREAD

**Issue by gannon93** [gannon93/Kharon#1]
Available Features:

  - [x] Format `info.json` files in the new v3 format

Upcoming Features:

  - [ ] Format v3 formatted `info.json` files to v2 format. _I don't know why you'd want this..._
  - [ ] Export new `info.json` file (backup old with `.bak` suffix)

Down Road:

  - [ ] Add `__init__.py` with standard bot init
  - [ ] Format core file `import` statements for `dataIO` and `utils`
